server:
  servlet:
    context-path: '/'
  port: 1024
  tomcat:
    basedir: $profile/logs/smart_admin_v2/pre/tomcat-logs
    accesslog:
      enabled: true
      pattern: '%t %{X-Forwarded-For}i %a "%r" %s %D (%D ms)'

spring:
  profiles:
    active: '@profiles.active@'
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
project:
  name: sa-admin
  module: net.lab1024.sa.admin.module

swagger:
  host: localhost:${server.port}
  tag-class: net.lab1024.sa.admin.constant.AdminSwaggerTagConst

