spring:
  datasource:
    user:
      url: jdbc:p6spy:mysql://localhost:3306/smart_admin_v2?autoReconnect=true&useServerPreparedStmts=false&rewriteBatchedStatements=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: zyc992329
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    ema:
      url: jdbc:sqlite:database/smart_admin_v2.db
      driver-class-name: org.sqlite.JDBC
      connection-init-sql: PRAGMA journal_mode=DELETE
    initial-size: 2
    min-idle: 2
    max-active: 10
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    filters: stat
    druid:
      username: druid
      password: 1024
      login:
        enabled: false
      method:
        pointcut: net.lab1024.sa..*Service.*
  # JPA Setting
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLiteDialect
    show-sql: true
  # mvc swagger bugfix
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # redis Configuration
  redis:
    database: 1
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 5
        min-idle: 1
        max-idle: 3
        max-wait: 30000ms
    port: 6379
    timeout: 10000ms
  #    password: 123456

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  # json serialization
  jackson:
    serialization:
      write-enums-using-to-string: true
      write-dates-as-timestamps: false
    deserialization:
      read-enums-using-to-string: true
      fail-on-unknown-properties: false
    default-property-inclusion: always
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # Cache
  cache:
    type: caffeine

#swagger
logging:
  level:
    springfox:
      documentation:
        spring:
          web:
            readers:
              operation:
                CachingOperationNameGenerator: warn
            scanners:
              ApiListingReferenceScanner: warn

# swagger Config
swagger:
  title: SmartAdmin
  description: SmartAdmin 2.0
  version: 2.0
  host: localhost:${server.port}
  package: net.lab1024.sa
  tag-class: net.lab1024.sa.common.constant.SwaggerTagConst
  team-url: https://www.1024lab.net/

# RestTemplate
http:
  pool:
    max-total: 20
    connect-timeout: 50000
    read-timeout: 50000
    write-timeout: 50000
    keep-alive: 300000

# token config
token:
  key: sa-jwt-key
  expire-day: 7

# Cross-region config
access-control-allow-origin: '*'

# heart beat config
heart-beat:
  interval-seconds: 60

# hot-reload config
reload:
  interval-seconds: 60