server:
  servlet:
    context-path: '/'          # The root context path for the servlet.
  port: 1024                  # Port on which the server is running.
  # Tomcat configuration, mainly for configuring access logs (useful for future error troubleshooting).
  tomcat:
    basedir: $profile/logs/smart_admin_v2/dev/tomcat-logs  # Base directory for Tomcat logs.
    accesslog:
      enabled: true           # Enable access logging.
      pattern: '%t %{X-Forwarded-For}i %a "%r" %s %D (%D ms)'  # Log pattern format.

spring:
  profiles:
    active: '@profiles.active@'  # The active profile for the application.
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # Naming strategy for Hibernate.

# Project configuration
project:
  name: sa-admin   # Name of the project.
  module: net.lab1024.sa.admin.module   # Module path for the project.

# Swagger documentation
swagger:
  host: localhost:${server.port}   # Host for the Swagger UI.
  tag-class: net.lab1024.sa.admin.constant.AdminSwaggerTagConst  # Class that contains tags for the Swagger documentation.

